[package]
name = "mamoru-sui-sniffer"
version = "0.1.0"
edition = "2021"
resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4" }
fastcrypto = { workspace = true }
mamoru-sniffer = { workspace = true }
mamoru-sui-types = { workspace = true }
move-core-types = { workspace = true }
sui-types = { path = "../sui-types" }
tracing = "0.1"
thiserror = "1.0"
tokio = "1"
rayon = "1.6.1"
