name: "Build docker image"
on:
  push:
    branches:
      - main
      - devnet
      - testnet
     # - testnet-v1.*

env:
  REPOSITORY: mamorufoundation/sui-sniffer

concurrency:
  # cancel redundant builds on PRs (only on PR, not on branches)
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Start docker service
        run: sudo service docker start || true

      - uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: |
            ${{ secrets.MAMORU_CORE_KEY }}
            ${{ secrets.VALIDATION_CHAIN_KEY }}

      - name: Prepare git and ssh config for build context
        run: |
          mkdir root-config
          cp -r ~/.gitconfig  ~/.ssh root-config/

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date -u +'%Y-%m-%d')"

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/sui-node/Dockerfile
          build-args: |
            GIT_REVISION=${{ github.sha }}
            BUILD_DATE=${{ steps.date.outputs.date }}
            PROFILE=release
          push: true
          tags: |
            ${{ env.REPOSITORY }}:latest
            ${{ env.REPOSITORY }}:${{ github.sha }}
          ssh: |
            default=${{ env.SSH_AUTH_SOCK }}
